#! /bin/zsh
ws1= # main
ws2= # web
ws3= # mail
ws4= # code
ws5= # math [infinity]  (term icon)
ws6= # media
ws7= # misc  (9 squares icon)
ws8= # notes/docs  (pdf icon)
ws9= # settings  (1 cog settings icon)
ws10= # trash
#bspc monitor -d "α" "β" "γ" "δ" "ε" "ζ"

# bspc monitor -d "i" "ii" "iii" "iv" "v" "vi" "vii" "viii" "ix" "x"
bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws10
# bspc config top_padding 5
# bspc config left_padding 5
# bspc config right_padding 5
# bspc config bottom_padding 5


desktop_config() {
    bspc config $1 $2
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}
desktop_config border_width 6
desktop_config window_gap 12


#bspc config border_width        5
#bspc config window_gap          12



bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
#bspc config auto_alternate true
#bspc config auto_cancel true


#Rules

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop=^3
bspc rule -a Thunar desktop=^4
bspc rule -a Vlc desktop=^6
bspc rule -a VirtualBox desktop=^10
bspc rule -a Lxappearance desktop=^5
bspc rule -a Nitrogen desktop=^9
bspc rule -a Feh desktop=^6
bspc rule -a Gpicview desktop=^6
bspc rule -a qbittorrent desktop=^9


compton --config ~/.config/compton.conf -b -c &
mpd &
feh --bg-scale ~/backgrounds/manganese.jpg

/home/dinesh/bin/panel &
